### ISSUE TITLE
Sugar Cane Not Transferring to Inventory Properly

### ISSUE THREAD

**Issue by NolanMC** [ThePhilderbeast/AutoPickup#14]
How to produce the issue: When you hit a Sugar Cane that is 3 blocks tall in the middle, only the middle sugar cane reed will transfer into your inventory. The top sugar cane will drop like a regular entity. 

What should happen?: The middle and the top of the 3 block tall sugar cane should transfer to inventory, not just the middle.

I was personally able to reproduce this in 3.8 and 5.0.3.

**Comment by CultivateMC** [comment]
Is this going to be fixed anytime soon? @ThePhilderbeast

**Comment by ThePhilderbeast** [comment]
probably not, I have looked in to this, however I'm still not sure how I'm going to fix this as the player is not directly breaking the block.

**Comment by CultivateMC** [comment]
I had a 3rd party developer fix this issue last year for me with the old src (Since I run a server that is somewhat dependent on the feature of being able to autopickup Sugar Cane) and that commit could be found here: https://github.com/traceurkid/AutoPickup/commit/2bc3eca28d68c163fb1d81b2ac5fd2f36df8e621#diff-758922f2ece7cc11fe91cee82ae007c8L8

I don't know if this would be of any help but I figured I would pass it along,

**Comment by ThePhilderbeast** [comment]
thanks for that. i have made a pull request for that commit. ill check it tonight after work

**Comment by ThePhilderbeast** [comment]
I have put the relevant code in the repo, can you test it out for me and verify its working as desired and ill push a release out.

**Comment by CultivateMC** [comment]
@ThePhilderbeast code works to my knowledge. Sorry for the delay
